// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xczdwucsptkzkyzkjjne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjemR3dWNzcHRremt5emtqam5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDc4NDUsImV4cCI6MjA3Mzg4Mzg0NX0.Vry2euoqLjvagDps94ggDanodQFMclPMZH3Trt5-nEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});